version: '3'

services:
  api:
    container_name: api_container
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    restart: on-failure
    ports:
      - "8080:8080"
    expose:
      - "8080"
    depends_on:
      - postgresdb

  postgresdb:
    container_name: postgresdb_container
    build:
      context: ./database/postgres
      dockerfile: Dockerfile
    env_file:
      - ./database/postgres/.env
    restart: on-failure
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - postgresdb-data:/var/lib/postgresql/data

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin_container
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
  #     - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
  #   restart: on-failure
  #   ports:
  #     - "5050:80"
  #   volumes:
  #      - pgadmin:/root/.pgadmin

volumes:
  postgresdb-data:
  # pgadmin:
