// Code generated by mockery v1.0.0. DO NOT EDIT.

package healthcheck

import mock "github.com/stretchr/testify/mock"

// MockService is an autogenerated mock type for the IService type
type MockService struct {
	mock.Mock
}

// GetStatus provides a mock function with given fields:
func (_m *MockService) GetStatus() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
