// Code generated by mockery v2.16.0. DO NOT EDIT.

package healthcheck

import mock "github.com/stretchr/testify/mock"

// Service is an autogenerated mock type for the IService type
type Service struct {
	mock.Mock
}

// GetStatus provides a mock function with given fields:
func (_m *Service) GetStatus() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewService interface {
	mock.TestingT
	Cleanup(func())
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewService(t mockConstructorTestingTNewService) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
