basePath: /
definitions:
  message.Message:
    properties:
      message:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: icaroribeiro@hotmail.com
    name: API Support
  description: A REST API developed using Golang, Json Web Token and PostgreSQL database.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: New Go Code Challenge Template API
  version: "1.0"
paths:
  /status:
    get:
      operationId: GetStatus
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/message.Message'
      summary: API endpoint used to verify if the service has started up correctly and is ready to accept requests.
      tags:
      - health check
schemes:
- http
swagger: "2.0"
tags:
- description: It refers to the operation related to health check.
  name: health check
- description: It refers to the operations related to authentication.
  name: authentication
